### ISSUE TITLE
Support PHPStan 0.11 and all Zend ServiceManager and PluginManager

### ISSUE THREAD

**Issue by Slamdunk** [bitwombat/phpstan-zend-framework#3]
Hi, I'm rewriting this library to support latest version of PHPStan, and along controller plugins, also all other service manager and plugin managers of Zend\Mvc (see for example [ModuleManagerFactory](https://github.com/zendframework/zend-mvc/blob/master/src/Service/ModuleManagerFactory.php)).

I see there's no commit since 2017, and this tells me you are probably not active anymore maintaining this tool.
I propose myself here to:

1. Fork this library
1. Add support for latest PHPStan versions
1. Keep the extension up to date to future PHPStan versions
1. Add support for all Zend\Mvc service manager and plugin managers
1. Add tests
1. Publish the library under PHPStan ecosystem (at the time of writing, its [README.md](https://github.com/phpstan/phpstan/blob/master/README.md))
1. Publish the library under my name (only to ease the library management)

The updated library will be a fork and your contribution will be kept under composer authors, alongside @MichaelGooden

Do I have your permission to proceed @bitwombat ?

At the end of the process, I would also like to ask you to archive this library and to pinpoint in the README the new library link as a replacement.

Best regards, and thank you for your [efforts on PHPStan](https://github.com/phpstan/phpstan/issues?q=is%3Aissue+author%3Abitwombat+is%3Aclosed).

**Comment by bitwombat** [comment]
Hi @Slamdunk - yes, please fork, and thanks for the effort! I didn't know we were supposed to ask before forking.

Others have done work since me. Don't miss the unstoppable @asgrim and @MichaelGooden whose work is at:
https://github.com/asgrim/phpstan-zend-framework
and
https://github.com/MichaelGooden/phpstan-zend-mvc

**Comment by Slamdunk** [comment]
I've asked because my intention is to have an near-to-official extension, and doing so without informing you would be unfair to me.

I'll update you as soon as I'm ready, thank you :+1:

**Comment by asgrim** [comment]
Wow, I literally don't remember writing that code. Feel free to use mine :+1:

**Comment by MichaelGooden** [comment]
@Slamdunk feel free to use whatever you need from my fork too! Change in employment means I am suddenly not using ZF3 at all, so I have not been updating my fork.

**Comment by Slamdunk** [comment]
First release of 
https://github.com/phpstan/phpstan/pull/2193
